# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1E1E2E"

# Main text color
theme[main_fg]="#CDD6F4"

# Title color for boxes
theme[title]="#CDD6F4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#89B4FA"

# Background color of selected item in processes box
theme[selected_bg]="#CBA6F7"

# Foreground color of selected item in processes box
theme[selected_fg]="#1E1E2E"

# Color of inactive/disabled text
theme[inactive_fg]="#6C7086"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#F5C2E7"

# Background color of the percentage meters
theme[meter_bg]="#45475A"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#F5C2E7"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#CBA6F7" # Mauve
theme[mem_box]="#A6E3A1" # Green
theme[net_box]="#EBA0AC" # Maroon
theme[proc_box]="#89B4FA" # Blue

# Box divider line and small boxes line color
theme[div_line]="#6C7086"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#A6E3A1"
theme[temp_mid]="#F9E2AF"
theme[temp_end]="#F38BA8"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#94E2D5"
theme[cpu_mid]="#74C7EC"
theme[cpu_end]="#B4BEFE"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#CBA6F7"
theme[free_mid]="#B4BEFE"
theme[free_end]="#89B4FA"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#74C7EC"
theme[cached_mid]="#89B4FA"
theme[cached_end]="#B4BEFE"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#FAB387"
theme[available_mid]="#EBA0AC"
theme[available_end]="#F38BA8"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#A6E3A1"
theme[used_mid]="#94E2D5"
theme[used_end]="#89DCEB"

# Download graph colors (Peach -> Red)
theme[download_start]="#FAB387"
theme[download_mid]="#EBA0AC"
theme[download_end]="#F38BA8"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#A6E3A1"
theme[upload_mid]="#94E2D5"
theme[upload_end]="#89DCEB"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#74C7EC"
theme[process_mid]="#B4BEFE"
theme[process_end]="#CBA6F7"
